export const displayNames: Record<string, string> = {
  add: "Agregar",
  shop: "Tienda",
  user: "Usuario",
  categories: "Categorías",
  subcategories: "Subcategorías",
  products: "Productos",
  brands: "Marcas",
  sizes: "Talles",
  profile: "Perfil",
  prices: "Precios",
  sales: "Ventas",
  reports: "Reportes",
  support: "Soporte",
  createemployee: "Nuevo empleado",
  addProduct: "Agregar producto",
  addVariant: "Agregar variante",
  addcategory: "Agregar categoría",
  addsubcategory: "Agregar subcategoría",
  addbrand: "Agregar marca",
  addsize: "Agregar talle",
  editlists: "Editar listas",
  cashcount: "Arqueo de caja",
  cashregister: "Corte de caja",
  orders: "Órdenes",
  settingsmanager: "Configuraciones",
};